runtime: nodejs18

service: default
env: standard
instance_class: F1
env_variables:
  PORT: 8080
  ENVIRONMENT: "development"
  MONGODB_URI: "mongodb+srv://ashis:admin@cluster0.08el1bo.mongodb.net"

handlers:
  - url: ".*"
    script: auto
    secure: always
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
